import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import { createServer as createViteServer } from 'vite';
import dotenv from 'dotenv';

// Load environment variables
dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Body parsing middleware
  app.use(express.json());

  // API Route: Send Email Alert (Secure Server-Side Proxy)
  app.post('/api/send-email', async (req, res) => {
    try {
      const { name, email, phone, date, timeSlot, projectType, budget, details, source } = req.body;

      if (!name || !email) {
        return res.status(400).json({ 
          success: false, 
          error: 'Name and email are required fields.' 
        });
      }

      const recipient = 'b.v.sandeepreddy21@gmail.com';
      const subject = `📅 [Sandeep Portfolio] ${source === 'booking' ? 'New Consultation Booked' : 'New Contact Inquiry'}: ${name}`;
      
      // Construct a professional HTML email layout with client specifications
      const emailHtml = `
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #E5E7EB; border-radius: 16px; background-color: #FFFFFF; color: #1F2937;">
          <!-- Header -->
          <div style="border-bottom: 2px solid #FF7A1A; padding-bottom: 16px; margin-bottom: 24px;">
            <h2 style="font-size: 20px; font-weight: 800; color: #111827; margin: 0; text-transform: uppercase; tracking-wider; font-family: monospace;">
              ${source === 'booking' ? '⚡ CONSULTATION ALERTER' : '✉️ CONTACT FORM ALERTER'}
            </h2>
            <p style="font-size: 12px; color: #6B7280; margin: 4px 0 0 0;">Received from Sandeep Reddy Portfolio</p>
          </div>
          
          <!-- Content Specs -->
          <div style="margin-bottom: 24px; space-y: 12px;">
            <p style="font-size: 14px; margin: 0 0 12px 0;"><strong>Client Name:</strong> <span style="color: #111827; font-weight: 600;">${name}</span></p>
            <p style="font-size: 14px; margin: 0 0 12px 0;"><strong>Client Email:</strong> <a href="mailto:${email}" style="color: #FF7A1A; text-decoration: none; font-weight: 600;">${email}</a></p>
            ${phone ? `<p style="font-size: 14px; margin: 0 0 12px 0;"><strong>Phone Number:</strong> <a href="tel:${phone}" style="color: #FF7A1A; text-decoration: none; font-weight: 600;">${phone}</a></p>` : ''}
            
            ${source === 'booking' ? `
              <p style="font-size: 14px; margin: 0 0 12px 0;"><strong>Desired Service:</strong> <span style="color: #111827; font-weight: 600;">${projectType}</span></p>
              <p style="font-size: 14px; margin: 0 0 12px 0;"><strong>Scheduled Date:</strong> <span style="color: #111827; font-weight: 600;">${date}</span></p>
              <p style="font-size: 14px; margin: 0 0 12px 0;"><strong>Time Slot:</strong> <span style="color: #111827; font-weight: 600;">${timeSlot}</span></p>
            ` : `
              <p style="font-size: 14px; margin: 0 0 12px 0;"><strong>Inquiry Type / Service:</strong> <span style="color: #111827; font-weight: 600;">${projectType || 'General Inquiry'}</span></p>
            `}
            
            <p style="font-size: 14px; margin: 0 0 12px 0;"><strong>Project Budget Scope:</strong> <span style="background-color: #FFF7F2; color: #FF7A1A; padding: 4px 8px; border-radius: 6px; font-weight: bold; font-size: 12px;">${budget || 'Not specified'}</span></p>
          </div>

          <!-- Description Section -->
          <div style="background-color: #F9FAFB; border: 1px solid #F3F4F6; border-radius: 12px; padding: 16px; margin-bottom: 24px;">
            <h4 style="font-size: 12px; font-weight: 700; text-transform: uppercase; color: #4B5563; margin: 0 0 8px 0; font-family: monospace;">
              Client Specifications / Requirements:
            </h4>
            <p style="font-size: 13px; line-height: 1.6; color: #374151; margin: 0; white-space: pre-wrap;">
              ${details || 'No detailed specifications provided.'}
            </p>
          </div>

          <!-- Footer Metadata -->
          <div style="border-top: 1px solid #E5E7EB; padding-top: 16px; font-size: 11px; color: #9CA3AF; text-align: center;">
            <p style="margin: 0 0 4px 0;">This notification is auto-generated by the Sandeep Portfolio Backend.</p>
            <p style="margin: 0;">Timestamp: ${new Date().toISOString()}</p>
          </div>
        </div>
      `;

      const apiKey = process.env.RESEND_API_KEY;

      // === DEBUG LOGGING ===
      console.log('\n🔍 [EMAIL DEBUG] API Key loaded:', apiKey ? `Yes (starts with: ${apiKey.substring(0, 8)}...)` : 'NO - undefined/empty');
      console.log('🔍 [EMAIL DEBUG] Recipient:', recipient);
      console.log('🔍 [EMAIL DEBUG] Request body received:', { name, email, source });

      if (!apiKey || apiKey === 'MY_RESEND_API_KEY' || apiKey.trim() === '') {
        console.log('\n=============================================');
        console.log('📬 [EMAIL ALERT SIMULATION] - API key not configured!');
        console.log(`To: ${recipient}`);
        console.log(`Subject: ${subject}`);
        console.log(`Payload:`, { name, email, date, timeSlot, projectType, budget, details });
        console.log('=============================================\n');

        return res.status(200).json({
          success: true,
          simulated: true,
          message: 'Email notification simulated successfully in server logs. Configure RESEND_API_KEY for actual email delivery.'
        });
      }

      console.log('🔍 [EMAIL DEBUG] Sending LIVE email via Resend API...');

      // Live integration using Resend's API via fetch
      const emailPayload = {
        from: 'Sandeep Portfolio <onboarding@resend.dev>',
        to: recipient,
        subject: subject,
        html: emailHtml
      };

      console.log('🔍 [EMAIL DEBUG] Payload to Resend:', { from: emailPayload.from, to: emailPayload.to, subject: emailPayload.subject });

      const response = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(emailPayload)
      });

      const responseData = await response.json() as any;

      console.log('🔍 [EMAIL DEBUG] Resend HTTP Status:', response.status);
      console.log('🔍 [EMAIL DEBUG] Resend Full Response:', JSON.stringify(responseData, null, 2));

      if (response.ok) {
        console.log('✅ [EMAIL SUCCESS] Email sent! ID:', responseData?.id);
        return res.status(200).json({
          success: true,
          data: responseData
        });
      } else {
        const errMsg = responseData?.message || responseData?.name || JSON.stringify(responseData);
        console.error('❌ Resend API Error:', errMsg, '| Full response:', JSON.stringify(responseData));
        return res.status(500).json({
          success: false,
          error: `Resend error: ${errMsg}. Check that your RESEND_API_KEY is valid and the recipient email matches your Resend account's verified address.`
        });
      }

    } catch (error: any) {
      console.error('Failed to process send-email endpoint:', error);
      return res.status(500).json({
        success: false,
        error: error.message || 'Internal server error occurred.'
      });
    }
  });

  // Vite integration middleware
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server running on port ${PORT}`);
  });
}

startServer();
