import type { VercelRequest, VercelResponse } from '@vercel/node';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // Only allow POST
  if (req.method !== 'POST') {
    return res.status(405).json({ success: false, error: 'Method not allowed' });
  }

  try {
    const { name, email, phone, date, timeSlot, projectType, budget, details, source } = req.body;

    if (!name || !email) {
      return res.status(400).json({
        success: false,
        error: 'Name and email are required fields.'
      });
    }

    const recipient = 'b.v.sandeepreddy21@gmail.com';
    const subject = `📅 [Sandeep Portfolio] ${source === 'booking' ? 'New Consultation Booked' : 'New Contact Inquiry'}: ${name}`;

    const emailHtml = `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #E5E7EB; border-radius: 16px; background-color: #FFFFFF; color: #1F2937;">
        <div style="border-bottom: 2px solid #FF7A1A; padding-bottom: 16px; margin-bottom: 24px;">
          <h2 style="font-size: 20px; font-weight: 800; color: #111827; margin: 0; text-transform: uppercase; font-family: monospace;">
            ${source === 'booking' ? '⚡ CONSULTATION ALERTER' : '✉️ CONTACT FORM ALERTER'}
          </h2>
          <p style="font-size: 12px; color: #6B7280; margin: 4px 0 0 0;">Received from Sandeep Reddy Portfolio</p>
        </div>

        <div style="margin-bottom: 24px;">
          <p style="font-size: 14px; margin: 0 0 12px 0;"><strong>Client Name:</strong> <span style="color: #111827; font-weight: 600;">${name}</span></p>
          <p style="font-size: 14px; margin: 0 0 12px 0;"><strong>Client Email:</strong> <a href="mailto:${email}" style="color: #FF7A1A; text-decoration: none; font-weight: 600;">${email}</a></p>
          ${phone ? `<p style="font-size: 14px; margin: 0 0 12px 0;"><strong>Phone Number:</strong> <a href="tel:${phone}" style="color: #FF7A1A; text-decoration: none; font-weight: 600;">${phone}</a></p>` : ''}

          ${source === 'booking' ? `
            <p style="font-size: 14px; margin: 0 0 12px 0;"><strong>Desired Service:</strong> <span style="color: #111827; font-weight: 600;">${projectType}</span></p>
            <p style="font-size: 14px; margin: 0 0 12px 0;"><strong>Scheduled Date:</strong> <span style="color: #111827; font-weight: 600;">${date}</span></p>
            <p style="font-size: 14px; margin: 0 0 12px 0;"><strong>Time Slot:</strong> <span style="color: #111827; font-weight: 600;">${timeSlot}</span></p>
          ` : `
            <p style="font-size: 14px; margin: 0 0 12px 0;"><strong>Inquiry Type / Service:</strong> <span style="color: #111827; font-weight: 600;">${projectType || 'General Inquiry'}</span></p>
          `}

          <p style="font-size: 14px; margin: 0 0 12px 0;"><strong>Project Budget Scope:</strong> <span style="background-color: #FFF7F2; color: #FF7A1A; padding: 4px 8px; border-radius: 6px; font-weight: bold; font-size: 12px;">${budget || 'Not specified'}</span></p>
        </div>

        <div style="background-color: #F9FAFB; border: 1px solid #F3F4F6; border-radius: 12px; padding: 16px; margin-bottom: 24px;">
          <h4 style="font-size: 12px; font-weight: 700; text-transform: uppercase; color: #4B5563; margin: 0 0 8px 0; font-family: monospace;">
            Client Specifications / Requirements:
          </h4>
          <p style="font-size: 13px; line-height: 1.6; color: #374151; margin: 0; white-space: pre-wrap;">
            ${details || 'No detailed specifications provided.'}
          </p>
        </div>

        <div style="border-top: 1px solid #E5E7EB; padding-top: 16px; font-size: 11px; color: #9CA3AF; text-align: center;">
          <p style="margin: 0 0 4px 0;">This notification is auto-generated by the Sandeep Portfolio Backend.</p>
          <p style="margin: 0;">Timestamp: ${new Date().toISOString()}</p>
        </div>
      </div>
    `;

    const apiKey = process.env.RESEND_API_KEY;

    if (!apiKey || apiKey === 'MY_RESEND_API_KEY' || apiKey.trim() === '') {
      // Simulate success when no API key is configured
      return res.status(200).json({
        success: true,
        simulated: true,
        message: 'Email notification simulated. Configure RESEND_API_KEY environment variable on Vercel for actual email delivery.'
      });
    }

    // Send email via Resend API
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        from: 'Sandeep Portfolio <onboarding@resend.dev>',
        to: recipient,
        subject: subject,
        html: emailHtml
      })
    });

    const responseData = await response.json();

    if (response.ok) {
      return res.status(200).json({
        success: true,
        data: responseData
      });
    } else {
      const errMsg = (responseData as any)?.message || (responseData as any)?.name || JSON.stringify(responseData);
      return res.status(500).json({
        success: false,
        error: `Resend error: ${errMsg}`
      });
    }

  } catch (error: any) {
    console.error('Failed to process send-email:', error);
    return res.status(500).json({
      success: false,
      error: error.message || 'Internal server error occurred.'
    });
  }
}
